name: active-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - numpy
  - scikit-learn
  - pip
  - matplotlib
  - tqdm
  - pandas
  - autopep8
  - pytorch
  - tabulate
  - pip:
    - imbalanced-learn
