name: active-learning
channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python
  - numpy
  - scikit-learn
  - pip
  - matplotlib
  - tqdm
  - pandas
  - autopep8
  - pytorch-cuda=11.8
  - pytorch
  - torchvision
  - tabulate
  - seaborn
  - pip:
    - imbalanced-learn
